### ISSUE TITLE
change 'interface' name or move to sub-package

### ISSUE THREAD

**Issue by hainm** [pengfeili1/pymsmt#1]
hi,

it's me, Hai from Case group.

I saw "interface" package in $AMBERHOME/lib/python3.4/site-packages/

In my opinion, you should rename this package, or put it in `pymsmt` namespace. The first time I saw it, I have no idea where "interface" comes from.

Hai

**Comment by pengfeili1** [comment]
Hi Hai,

Thanks for your suggestion. It would be safer to treat the directory with another name. I will change it in pymsmt in github.

Best,
Pengfei

**Comment by hainm** [comment]
@pengfeili1  is there any reason to make different packages in a single repos?

Like scipy, it has several ones but still in `scipy` namespace.
